spring.application.name=contrucoes

spring.datasource.url=jdbc:postgresql://dpg-cvpet1buibrs73fvasr0-a:5432/construcoes
spring.datasource.username=admin
spring.datasource.password=AahrTDgfhewI1D9RaN0Z1vTxo7hKhcKc
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect